version: "3"
services:
  dynamo_admin:
    build:
      context: .
      dockerfile: Dockerfile.dynamo_admin
    environment:
      - AWS_REGION=ap-northeast-1
      - DYNAMO_ENDPOINT=http://dynamo:8000
    ports:
      - "8001:8001"

  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    environment:
      DEFAULT_REGION: ap-northeast-1
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
    ports:
      - "3000:3000"
